name: MacOS CI
on:
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/macos.yml'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
        qt_ver: [5.15.2]
        qt_arch: [clang_64]
    env:
      targetName: ppin
    steps:
      # macos 11.0 默认环境变了,要指定
      - name: Prepare Env
        if: ${{ matrix.os == 'macos-11.0' }}
        run: |
          softwareupdate --all --install --force
          sudo xcode-select --print-path
          sudo xcode-select --switch /Library/Developer/CommandLineTools
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 1
      - name: Build MacOS
        run: |
          qmake
          make
      # 打包
      - name: Package
        run: |
          # 拷贝依赖
          macdeployqt bin/release/${targetName}.app -qmldir=. -verbose=1 -dmg
      # 上传artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.targetName }}_${{ matrix.os }}.zip
          path: bin/release/${{ env.targetName }}.app
      # tag 上传Release
      - name: Upload Release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/release/${{ env.targetName }}.dmg
          asset_name: ${{ env.targetName }}_${{ matrix.os }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
