name: Ubuntu Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
          version: 5.15.2

    - name: Install SSL
      run: sudo apt install libssl-dev -y

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 1

    - name: Build Ubuntu
      run: |
        qmake
        make -j8

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/ppin